package br.com.proj.tasker.model;
// Generated Nov 11, 2014 9:48:22 PM by Hibernate Tools 3.6.0

/**
 * Ativmembros generated by hbm2java
 */
public class Ativmembros  implements java.io.Serializable {


     private int idAtiv;
     private Cargo cargo;
     private Pessoa pessoa;
     private Perfil perfil;
     private Grupo grupo;
     
     
    public Ativmembros() {
    }

	
    public Ativmembros(int idAtiv, Pessoa pessoa, Perfil perfil, Grupo grupo) {
        this.idAtiv = idAtiv;
        this.pessoa = pessoa;
        this.perfil = perfil;
        this.grupo = grupo;
    }
   
    public int getIdAtiv() {
        return this.idAtiv;
    }
    
    public void setIdAtiv(int idAtiv) {
        this.idAtiv = idAtiv;
    }
    public Cargo getCargo() {
        if (cargo == null ){
            cargo = new Cargo();
        }
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }




}


