package br.com.proj.tasker.model;
// Generated Oct 21, 2014 12:09:02 AM by Hibernate Tools 3.6.0



/**
 * Ativacao generated by hbm2java
 */
public class Ativacao  implements java.io.Serializable {


     private String chave;
     private Usuario usuario;

    public Ativacao() {
    }

	
    public Ativacao(String chave) {
        this.chave = chave;
    }
    public Ativacao(String chave, Usuario usuario) {
       this.chave = chave;
       this.usuario = usuario;
    }
   
    public String getChave() {
        return this.chave;
    }
    
    public void setChave(String chave) {
        this.chave = chave;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}

