package br.com.proj.tasker.model;
// Generated Nov 11, 2014 9:57:20 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Cargo generated by hbm2java
 */
public class Cargo implements java.io.Serializable {

     private Integer idCargo;
     private Pessoa pessoa;
     private Grupo grupo;
     private String nome;
     private Set tarefas = new HashSet(0);
     private Set ativmembroses = new HashSet(0);

    public Cargo() {
    }

	
    public Cargo(Integer idCargo, Pessoa pessoa, Grupo grupo, String nome) {
        this.idCargo = idCargo;
        this.pessoa = pessoa;
        this.grupo = grupo;
        this.nome = nome;
    }
    public Cargo(Integer idCargo, Pessoa pessoa, Grupo grupo, String nome, Set tarefas, Set ativmembroses) {
       this.idCargo = idCargo;
       this.pessoa = pessoa;
       this.grupo = grupo;
       this.nome = nome;
       this.tarefas = tarefas;
       this.ativmembroses = ativmembroses;
    }
   
    public Integer getIdCargo() {
        return this.idCargo;
    }
    
    public void setIdCargo(Integer idCargo) {
        this.idCargo = idCargo;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getTarefas() {
        return this.tarefas;
    }
    
    public void setTarefas(Set tarefas) {
        this.tarefas = tarefas;
    }
    public Set getAtivmembroses() {
        return this.ativmembroses;
    }
    
    public void setAtivmembroses(Set ativmembroses) {
        this.ativmembroses = ativmembroses;
    }
    
    
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (!(obj instanceof Cargo)) {
            return false;
        }
        Cargo other = (Cargo) obj;
        if (idCargo == null) {
            if (other.idCargo != null) {
                return false;
            }
        } else if (!idCargo.equals(other.idCargo)) {
            return false;
        }
        return true;
    }

}
