package br.com.proj.tasker.model;
// Generated Oct 21, 2014 12:16:00 AM by Hibernate Tools 3.6.0



/**
 * Cartaocred generated by hbm2java
 */
public class Cartaocred  implements java.io.Serializable {


     private int idCard;
     private Pessoa pessoa;
     private String num;
     private String codSeg;
     private String bandeira;

    public Cartaocred() {
    }

	
    public Cartaocred(Pessoa pessoa, String num, String codSeg, String bandeira) {
        this.pessoa = pessoa;
        this.num = num;
        this.codSeg = codSeg;
        this.bandeira = bandeira;
    }
    public Cartaocred(Pessoa pessoa, String num, String codSeg, String bandeira, String descricao) {
       this.pessoa = pessoa;
       this.num = num;
       this.codSeg = codSeg;
       this.bandeira = bandeira;
    }
   
    public int getIdCard() {
        return this.idCard;
    }
    
    public void setIdCard(int idCard) {
        this.idCard = idCard;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public String getNum() {
        return this.num;
    }
    
    public void setNum(String num) {
        this.num = num;
    }
    public String getCodSeg() {
        return this.codSeg;
    }
    
    public void setCodSeg(String codSeg) {
        this.codSeg = codSeg;
    }
    public String getBandeira() {
        return this.bandeira;
    }
    
    public void setBandeira(String bandeira) {
        this.bandeira = bandeira;
    }




}


