package br.com.proj.tasker.model;
// Generated Oct 21, 2014 12:16:00 AM by Hibernate Tools 3.6.0



/**
 * Endereco generated by hbm2java
 */
public class Endereco  implements java.io.Serializable {


     private int idEnd;
     private Pessoa pessoa;
     private String rua;
     private String bairro;
     private String num;
     private String cep;
     private String referencia;
     private String cidade;
     private String uf;

    public Endereco() {
    }

	
    public Endereco(Pessoa pessoa, String rua, String bairro, String num, String cep, String cidade, String uf) {
        this.pessoa = pessoa;
        this.rua = rua;
        this.bairro = bairro;
        this.num = num;
        this.cep = cep;
        this.cidade = cidade;
        this.uf = uf;
    }
    public Endereco(Pessoa pessoa, String rua, String bairro, String num, String cep, String referencia, String cidade, String uf, String descricao) {
       this.pessoa = pessoa;
       this.rua = rua;
       this.bairro = bairro;
       this.num = num;
       this.cep = cep;
       this.referencia = referencia;
       this.cidade = cidade;
       this.uf = uf;
    }
   
    public int getIdEnd() {
        return this.idEnd;
    }
    
    public void setIdEnd(int idEnd) {
        this.idEnd = idEnd;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public String getRua() {
        return this.rua;
    }
    
    public void setRua(String rua) {
        this.rua = rua;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getNum() {
        return this.num;
    }
    
    public void setNum(String num) {
        this.num = num;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }



}


