package br.com.proj.tasker.model;
// Generated Nov 18, 2014 4:26:26 PM by Hibernate Tools 3.6.0



/**
 * Logrealizacao generated by hbm2java
 */
public class Logrealizacao  implements java.io.Serializable {


     private int idReltar;
     private Pessoa pessoa;
     private Tarefa tarefa;

    public Logrealizacao() {
    }

    public Logrealizacao(int idReltar, Pessoa pessoa, Tarefa tarefa) {
       this.idReltar = idReltar;
       this.pessoa = pessoa;
       this.tarefa = tarefa;
    }
   
    public int getIdReltar() {
        return this.idReltar;
    }
    
    public void setIdReltar(int idReltar) {
        this.idReltar = idReltar;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Tarefa getTarefa() {
        return this.tarefa;
    }
    
    public void setTarefa(Tarefa tarefa) {
        this.tarefa = tarefa;
    }




}


