package br.com.proj.tasker.model;
// Generated Oct 21, 2014 12:16:00 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil implements java.io.Serializable {

    private Integer idPerf;
    private String descricao;
    private boolean mant;
    private boolean mantInteg;
    private boolean mantProj;
    private boolean cri;
    private boolean criProj;
    private boolean criTar;
    private boolean criPerf;
    private Set ativmembroses = new HashSet(0);

    public Perfil() {
    }

    public Perfil(Integer idPerf, String descricao, boolean mant, boolean mantInteg, boolean mantProj, boolean cri, boolean criProj, boolean criTar, boolean criPerf) {
        this.idPerf = idPerf;
        this.descricao = descricao;
        this.mant = mant;
        this.mantInteg = mantInteg;
        this.mantProj = mantProj;
        this.cri = cri;
        this.criProj = criProj;
        this.criTar = criTar;
        this.criPerf = criPerf;
    }

    public Perfil(Integer idPerf, String descricao, boolean mant, boolean mantInteg, boolean mantProj, boolean cri, boolean criProj, boolean criTar, boolean criPerf, Set ativmembroses) {
        this.idPerf = idPerf;
        this.descricao = descricao;
        this.mant = mant;
        this.mantInteg = mantInteg;
        this.mantProj = mantProj;
        this.cri = cri;
        this.criProj = criProj;
        this.criTar = criTar;
        this.criPerf = criPerf;
        this.ativmembroses = ativmembroses;
    }

    public Integer getIdPerf() {
        return this.idPerf;
    }

    public void setIdPerf(Integer idPerf) {
        this.idPerf = idPerf;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public boolean isMant() {
        return this.mant;
    }

    public void setMant(boolean mant) {
        this.mant = mant;
    }

    public boolean isMantInteg() {
        return this.mantInteg;
    }

    public void setMantInteg(boolean mantInteg) {
        this.mantInteg = mantInteg;
    }

    public boolean isMantProj() {
        return this.mantProj;
    }

    public void setMantProj(boolean mantProj) {
        this.mantProj = mantProj;
    }

    public boolean isCri() {
        return this.cri;
    }

    public void setCri(boolean cri) {
        this.cri = cri;
    }

    public boolean isCriProj() {
        return this.criProj;
    }

    public void setCriProj(boolean criProj) {
        this.criProj = criProj;
    }

    public boolean isCriTar() {
        return this.criTar;
    }

    public void setCriTar(boolean criTar) {
        this.criTar = criTar;
    }

    public boolean isCriPerf() {
        return this.criPerf;
    }

    public void setCriPerf(boolean criPerf) {
        this.criPerf = criPerf;
    }

    public Set getAtivmembroses() {
        return this.ativmembroses;
    }

    public void setAtivmembroses(Set ativmembroses) {
        this.ativmembroses = ativmembroses;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (!(obj instanceof Perfil)) {
            return false;
        }
        Perfil other = (Perfil) obj;
        if (idPerf == null) {
            if (other.idPerf != null) {
                return false;
            }
        } else if (!idPerf.equals(other.idPerf)) {
            return false;
        }
        return true;
    }

}
