package br.com.proj.tasker.model;
// Generated Oct 21, 2014 12:16:00 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {


     private Integer idPes;
     private Usuario usuario;
     private String nome;
     private String sobrenome;
     private Date dataNasc;
     private String cpf;
     private char sexo;
     private Set telefones = new HashSet(0);
     private Set ativmembroses = new HashSet(0);
     private Set cartaocreds = new HashSet(0);
     private Set logrealizacaos = new HashSet(0);
     private Set cargos = new HashSet(0);
     private Set enderecos = new HashSet(0);

    public Pessoa() {
    }

	
    public Pessoa(Usuario usuario, String nome, String sobrenome, Date dataNasc, String cpf, char sexo) {
        this.usuario = usuario;
        this.nome = nome;
        this.sobrenome = sobrenome;
        this.dataNasc = dataNasc;
        this.cpf = cpf;
        this.sexo = sexo;
    }
    public Pessoa(Integer idPes, Usuario usuario, String nome, String sobrenome, Date dataNasc, String cpf, char sexo, Set telefones, Set ativmembroses, Set cartaocreds, Set logrealizacaos, Set cargos, Set enderecos) {
       this.idPes = idPes;
       this.usuario = usuario;
       this.nome = nome;
       this.sobrenome = sobrenome;
       this.dataNasc = dataNasc;
       this.cpf = cpf;
       this.sexo = sexo;
       this.telefones = telefones;
       this.ativmembroses = ativmembroses;
       this.cartaocreds = cartaocreds;
       this.logrealizacaos = logrealizacaos;
       this.cargos = cargos;
       this.enderecos = enderecos;
    }
   
    public Integer getIdPes() {
        return this.idPes;
    }
    
    public void setIdPes(Integer idPes) {
        this.idPes = idPes;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSobrenome() {
        return this.sobrenome;
    }
    
    public void setSobrenome(String sobrenome) {
        this.sobrenome = sobrenome;
    }
    public Date getDataNasc() {
        return this.dataNasc;
    }
    
    public void setDataNasc(Date dataNasc) {
        this.dataNasc = dataNasc;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public char getSexo() {
        return this.sexo;
    }
    
    public void setSexo(char sexo) {
        this.sexo = sexo;
    }
    public Set getTelefones() {
        return this.telefones;
    }
    
    public void setTelefones(Set telefones) {
        this.telefones = telefones;
    }
    public Set getAtivmembroses() {
        return this.ativmembroses;
    }
    
    public void setAtivmembroses(Set ativmembroses) {
        this.ativmembroses = ativmembroses;
    }
    public Set getCartaocreds() {
        return this.cartaocreds;
    }
    
    public void setCartaocreds(Set cartaocreds) {
        this.cartaocreds = cartaocreds;
    }
    public Set getLogrealizacaos() {
        return this.logrealizacaos;
    }
    
    public void setLogrealizacaos(Set logrealizacaos) {
        this.logrealizacaos = logrealizacaos;
    }
    public Set getCargos() {
        return this.cargos;
    }
    
    public void setCargos(Set cargos) {
        this.cargos = cargos;
    }
    public Set getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Set enderecos) {
        this.enderecos = enderecos;
    }




}


