package br.com.proj.tasker.model;
// Generated Oct 21, 2014 12:16:00 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Plano generated by hbm2java
 */
public class Plano  implements java.io.Serializable {


     private Integer idPlan;
     private String nome;
     private float valor;
     private int NMember;
     private Set usuarios = new HashSet(0);

    public Plano() {
    }

	
    public Plano(Integer idPlan, String nome, float valor, int NMember) {
        this.idPlan = idPlan;
        this.nome = nome;
        this.valor = valor;
        this.NMember = NMember;
    }
    public Plano(Integer idPlan, String nome, float valor, int NMember, Set usuarios) {
       this.idPlan = idPlan;
       this.nome = nome;
       this.valor = valor;
       this.NMember = NMember;
       this.usuarios = usuarios;
    }
   
    public Integer getIdPlan() {
        return this.idPlan;
    }
    
    public void setIdPlan(Integer idPlan) {
        this.idPlan = idPlan;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public float getValor() {
        return this.valor;
    }
    
    public void setValor(float valor) {
        this.valor = valor;
    }
    public int getNMember() {
        return this.NMember;
    }
    
    public void setNMember(int NMember) {
        this.NMember = NMember;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }

    @Override  
    public boolean equals(Object obj){  
        if (this == obj)  
            return true;  
        if (obj == null)  
            return false;  
        if (!(obj instanceof Plano))  
            return false;  
        Plano other = (Plano) obj;  
        if (idPlan == null){  
            if (other.idPlan != null)  
                return false;  
        } else if (!idPlan.equals(other.idPlan))  
            return false;  
        return true;  
    } 

}


