package br.com.proj.tasker.model;
// Generated Nov 16, 2014 4:25:27 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tarefa generated by hbm2java
 */
public class Tarefa implements java.io.Serializable {

    private int idTar;
    private Cargo cargo;
    private Projeto projeto;
    private String descricao;
    private String observacoes;
    private Date dataCri;
    private String status;
    private Date dataFin;
    private Integer classificacao;
    private Date dataIni;
    private Set logrealizacaos = new HashSet(0);

    public Tarefa() {
    }

    public Tarefa(int idTar, Cargo cargo, Projeto projeto, String descricao, String observacoes, Date dataCri, String status) {
        this.idTar = idTar;
        this.cargo = cargo;
        this.projeto = projeto;
        this.descricao = descricao;
        this.observacoes = observacoes;
        this.dataCri = dataCri;
        this.status = status;
    }

    public Tarefa(int idTar, Cargo cargo, Projeto projeto, String descricao, String observacoes, Date dataCri, String status, Date dataFin, Integer classificacao, Date dataIni, Set logrealizacaos) {
        this.idTar = idTar;
        this.cargo = cargo;
        this.projeto = projeto;
        this.descricao = descricao;
        this.observacoes = observacoes;
        this.dataCri = dataCri;
        this.status = status;
        this.dataFin = dataFin;
        this.classificacao = classificacao;
        this.dataIni = dataIni;
        this.logrealizacaos = logrealizacaos;
    }

    public int getIdTar() {
        return this.idTar;
    }

    public void setIdTar(int idTar) {
        this.idTar = idTar;
    }

    public Cargo getCargo() {
        return this.cargo;
    }

    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }

    public Projeto getProjeto() {
        return this.projeto;
    }

    public void setProjeto(Projeto projeto) {
        this.projeto = projeto;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public String getObservacoes() {
        return this.observacoes;
    }

    public void setObservacoes(String observacoes) {
        this.observacoes = observacoes;
    }

    public Date getDataCri() {
        return this.dataCri;
    }

    public void setDataCri(Date dataCri) {
        this.dataCri = dataCri;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getDataFin() {
        return this.dataFin;
    }

    public void setDataFin(Date dataFin) {
        this.dataFin = dataFin;
    }

    public Integer getClassificacao() {
        return this.classificacao;
    }

    public void setClassificacao(Integer classificacao) {
        this.classificacao = classificacao;
    }

    public Date getDataIni() {
        return this.dataIni;
    }

    public void setDataIni(Date dataIni) {
        this.dataIni = dataIni;
    }

    public Set getLogrealizacaos() {
        return this.logrealizacaos;
    }

    public void setLogrealizacaos(Set logrealizacaos) {
        this.logrealizacaos = logrealizacaos;
    }

}
