package br.com.proj.tasker.model;
// Generated Oct 21, 2014 12:16:00 AM by Hibernate Tools 3.6.0



/**
 * Telefone generated by hbm2java
 */
public class Telefone  implements java.io.Serializable {


     private int idTel;
     private Pessoa pessoa;
     private String numero;
     private String tipo;

    public Telefone() {
    }

	
    public Telefone(Pessoa pessoa, String numero, String tipo) {
        this.pessoa = pessoa;
        this.numero = numero;
        this.tipo = tipo;
    }
   
    public int getIdTel() {
        return this.idTel;
    }
    
    public void setIdTel(int idTel) {
        this.idTel = idTel;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }



}


