package br.com.proj.tasker.model;
// Generated Oct 21, 2014 12:16:00 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUser;
     private Plano plano;
     private String senha;
     private String email;
     private String ativado;
     private Set pessoas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(Plano plano, String senha, String email, String ativado) {
        this.plano = plano;
        this.senha = senha;
        this.email = email;
        this.ativado = ativado;
    }
    public Usuario(Plano plano, String senha, String email, String ativado, Set pessoas) {
       this.plano = plano;
       this.senha = senha;
       this.email = email;
       this.ativado = ativado;
       this.pessoas = pessoas;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public Plano getPlano() {
        return this.plano;
    }
    
    public void setPlano(Plano plano) {
        this.plano = plano;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAtivado() {
        return this.ativado;
    }
    
    public void setAtivado(String ativado) {
        this.ativado = ativado;
    }
    public Set getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Set pessoas) {
        this.pessoas = pessoas;
    }




}


